// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: quote_service.proto

#include "quote_service.pb.h"
#include "quote_service.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace yuanda {

static const char* QuoteServer_method_names[] = {
  "/yuanda.QuoteServer/FetchQuote",
};

std::unique_ptr< QuoteServer::Stub> QuoteServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< QuoteServer::Stub> stub(new QuoteServer::Stub(channel));
  return stub;
}

QuoteServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_FetchQuote_(QuoteServer_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>* QuoteServer::Stub::FetchQuoteRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::yuanda::QuoteRequest, ::yuanda::Quote>::Create(channel_.get(), rpcmethod_FetchQuote_, context);
}

::grpc::ClientAsyncReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>* QuoteServer::Stub::AsyncFetchQuoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::yuanda::QuoteRequest, ::yuanda::Quote>::Create(channel_.get(), cq, rpcmethod_FetchQuote_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>* QuoteServer::Stub::PrepareAsyncFetchQuoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::yuanda::QuoteRequest, ::yuanda::Quote>::Create(channel_.get(), cq, rpcmethod_FetchQuote_, context, false, nullptr);
}

QuoteServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QuoteServer_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< QuoteServer::Service, ::yuanda::QuoteRequest, ::yuanda::Quote>(
          std::mem_fn(&QuoteServer::Service::FetchQuote), this)));
}

QuoteServer::Service::~Service() {
}

::grpc::Status QuoteServer::Service::FetchQuote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::yuanda::Quote, ::yuanda::QuoteRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace yuanda

