// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: quote_service.proto
#ifndef GRPC_quote_5fservice_2eproto__INCLUDED
#define GRPC_quote_5fservice_2eproto__INCLUDED

#include "quote_service.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace yuanda {

// Interface exported by the server.
class QuoteServer final {
 public:
  static constexpr char const* service_full_name() {
    return "yuanda.QuoteServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::yuanda::QuoteRequest, ::yuanda::Quote>> FetchQuote(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::yuanda::QuoteRequest, ::yuanda::Quote>>(FetchQuoteRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::yuanda::QuoteRequest, ::yuanda::Quote>> AsyncFetchQuote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::yuanda::QuoteRequest, ::yuanda::Quote>>(AsyncFetchQuoteRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::yuanda::QuoteRequest, ::yuanda::Quote>> PrepareAsyncFetchQuote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::yuanda::QuoteRequest, ::yuanda::Quote>>(PrepareAsyncFetchQuoteRaw(context, cq));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::yuanda::QuoteRequest, ::yuanda::Quote>* FetchQuoteRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::yuanda::QuoteRequest, ::yuanda::Quote>* AsyncFetchQuoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::yuanda::QuoteRequest, ::yuanda::Quote>* PrepareAsyncFetchQuoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>> FetchQuote(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>>(FetchQuoteRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>> AsyncFetchQuote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>>(AsyncFetchQuoteRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>> PrepareAsyncFetchQuote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>>(PrepareAsyncFetchQuoteRaw(context, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>* FetchQuoteRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>* AsyncFetchQuoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::yuanda::QuoteRequest, ::yuanda::Quote>* PrepareAsyncFetchQuoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FetchQuote_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status FetchQuote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::yuanda::Quote, ::yuanda::QuoteRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_FetchQuote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_FetchQuote() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FetchQuote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchQuote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::yuanda::Quote, ::yuanda::QuoteRequest>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchQuote(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::yuanda::Quote, ::yuanda::QuoteRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FetchQuote<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_FetchQuote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_FetchQuote() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FetchQuote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchQuote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::yuanda::Quote, ::yuanda::QuoteRequest>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace yuanda


#endif  // GRPC_quote_5fservice_2eproto__INCLUDED
